#ifndef COMMANDS_H
#define COMMANDS_H

enum tft_Commands{
    TEST,
    RESET,
    SET_BACKLIGHT,
    SET_ROTATION,
    FILL_SCREEN,
    READ_CURSOR,
    SET_CURSOR,
    SET_COLOR,
    SET_TEXT_COLOR,
    SET_TEXT_SIZE,
    SET_FONT,
    PRINT_LN,
    PRINT,
    DRAW_V_LINE,
    DRAW_H_LINE,
    DRAW_LINE,
    DRAW_RECT,
    FILL_RECT,
    DRAW_CIRCLE,
    FILL_CIRCLE,

    DRAW_TRIANGLE,
    FILL_TRIANGLE,
    DRAW_ARC,

    SET_BG_COLOR,
    DRAW_SMOOTH_CIRCLE,
    FILL_SMOOTH_CIRCLE,
    DRAW_SMOOTH_ROUND_RECT,
    FILL_SMOOTH_ROUND_RECT,
    DRAW_SMOOTH_ARC,

    DRAW_WIDE_LINE,
    DRAW_WEDGE_LINE,


    STREAM_START = 200,
    STREAM_END   = 201,
    DRAWTOSPRITE = 202,
    PUSHSPRITE   = 203,
    CHANGEBAUD   = 204
};






#endif // COMMANDS_H